# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  monkeyfactor.nl:
    site_hosts:
      - canonical: monkeyfactor.dev
        redirects:
          - www.monkeyfactor.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_user: monkeyfactor
    admin_email: martijnvhummel@hotmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      db_name: monkeyfactor_development
      db_user: monkeyfactor
      db_prefix: mnkfctr_
