# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: sXnT6CCb4g,<@4ne

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: dCYq,R*R{]%D)5Q5
    salt: "C32T=HN*L5>vdcF-a'B3=98L.!H;/*#VT9;'xw$m3-R<gLkQe8;YRSr"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  monkeyfactor.nl:
    admin_password: K%SMed}k&wb6P$3y
    env:
      db_password: KV~/"jufX#G7*8FN
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "qTuGCFCg{C>B@qMSDjCgYYh:v*MFhTfw#d#z%U4|2VlP#$UQN3AplFd;>U$`#@v4"
      secure_auth_key: "Os08H/Ld##!`=-`r/.-0aurc`H5+W1E4jFG?>)yVgg>u/g;Jpl1gDQ>,?Qn{Tc3g"
      logged_in_key: "Yk!EaN]y:2yih.d$.!Bfsbsj/SH&rLS4;b+p(^I:ew?%:>(qZ}![!T0/Y9Zh}%+;"
      nonce_key: "^{U8VPQ[>;ig6TR`/YO9@xUoGsQZzavqdG1.09kMEvZY-:`1AJ}G/w|!#=pIjCi3"
      auth_salt: "h{rOgj(a^bTzB0-Z;-6^uH-Sg3Uu!L|S<:P:)KJlXbJ1}gFlG1O<!c/B}kssN)nB"
      secure_auth_salt: "4n=@&+pGvN`SCB(Nkwa)9CT/>EVH%YdH^2NG=#{-Rr,8^a%v[Y-zW;zF(j!1o4h+"
      logged_in_salt: "M4$7My((d.^=Kn*@{bc.1W23|u25w:aiH60v3IiRG9s.cxbG}D|yPef8Y3ph8$wz"
      nonce_salt: "MF)qg^rFhmiE--O+Jb8.{_KnTM|>j`Fn]Y7`<`-EB{E4!rt(PU.Ct*TmtiBL[(Tl"
